// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const createDisabledClient = (): SupabaseClient<Database> => {
  const noop = () => undefined;
  return {
    auth: {
      getSession: async () => ({ data: { session: null } } as any),
      getUser: async () => ({ data: { user: null }, error: null } as any),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: noop } } } as any),
      signInWithPassword: async () => ({ error: { message: 'disabled' } } as any),
      signUp: async () => ({ error: { message: 'disabled' } } as any),
      signOut: async () => ({ error: null } as any),
    },
    from: () => ({ select: () => ({ eq: () => ({ single: async () => ({ data: null } as any) }) }) } as any),
    functions: { invoke: async () => ({ data: null, error: { message: 'disabled' } } as any) },
  } as unknown as SupabaseClient<Database>;
};

export const supabase: SupabaseClient<Database> =
  SUPABASE_URL && SUPABASE_ANON_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
        auth: { storage: localStorage, persistSession: true, autoRefreshToken: true },
      })
    : createDisabledClient();
