# Secret Scanning Configuration
# Exclude paths that may contain false positives or non-sensitive data

paths-ignore:
  # Documentation files (may contain example tokens)
  - "docs/**"
  - "*.md"
  - "*.rst"
  - "*.txt"

  # Test fixtures and mocks (may contain fake secrets)
  - "tests/fixtures/**"
  - "tests/mocks/**"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/*.spec.js"
  - "**/*.spec.ts"

  # Configuration examples
  - "*.example"
  - "*.sample"
  - "*.template"
  - "**/examples/**"

  # Generated files
  - "node_modules/**"
  - ".git/**"
  - "dist/**"
  - "build/**"
  - "coverage/**"

  # Log files
  - "*.log"
  - "logs/**"

  # Temporary files
  - "*.tmp"
  - "*.temp"
  - ".cache/**"
  - ".tmp/**"

# Enable custom patterns for additional secret detection
custom-patterns:
  # Private key patterns
  - name: "Private Key"
    regex: "-----BEGIN (RSA |OPENSSH |DSA |EC |PGP )?PRIVATE KEY-----"
    description: "Private key detected"

  # API key patterns
  - name: "API Key"
    regex: "(?i)(api[_-]?key|apikey)[\"'=:\\s]*([a-z0-9]{32,})"
    description: "API key detected"

  # Database connection strings
  - name: "Database Connection"
    regex: "(?i)(mongodb|mysql|postgresql)://[^\\s]+"
    description: "Database connection string detected"

  # JWT tokens
  - name: "JWT Token"
    regex: "eyJ[a-zA-Z0-9_-]*\\.eyJ[a-zA-Z0-9_-]*\\.[a-zA-Z0-9_-]*"
    description: "JWT token detected"
