# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false

flags:
  typescript:
    paths:
      - tools/
      - tests/
    carryforward: true
  python:
    paths:
      - automation/
      - .metaHub/scripts/
    carryforward: true

ignore:
  - "node_modules/**"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "templates/**"
  - "docs/**"

