---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supertool
  namespace: production
spec:
  interval: 10m0s
  timeout: 5m0s
  releaseName: supertool

  # Chart configuration
  chart:
    spec:
      chart: ./devops/kubernetes/helm/supertool
      sourceRef:
        kind: GitRepository
        name: supertool
        namespace: flux-system
      interval: 5m0s

  # Values override
  values:
    # Load from values-production.yaml
    replicaCount: 3

    image:
      repository: ghcr.io/username/supertool
      tag: "1.0.0"
      pullPolicy: IfNotPresent

    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi

    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 20

    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: supertool.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: supertool-tls
          hosts:
            - supertool.example.com

  # Install configuration
  install:
    remediation:
      retries: 3

  # Upgrade configuration
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true

  # Rollback configuration
  rollback:
    timeout: 5m0s
    cleanupOnFail: true

  # Test configuration
  test:
    enable: true
    timeout: 5m0s

  # Values files from Git
  valuesFrom:
    - kind: ConfigMap
      name: supertool-config
      valuesKey: values.yaml
      optional: true
