import fs from 'node:fs';
import path from 'node:path';
import { resolveTargetDir } from './config.js';
import { ensureDir } from './fs.js';

/**
 * Bootstrap a .metaHub workspace with required directories
 */
function bootstrap(targetDir: string): void {
  console.log(`Bootstrapping workspace at: ${targetDir}`);

  // Create main directory
  ensureDir(targetDir);

  // Create subdirectories
  const subdirs = ['tools', 'templates', 'ci', 'k8s', 'helm', 'monitoring', 'service', 'docs'];

  for (const subdir of subdirs) {
    const subdirPath = path.join(targetDir, subdir);
    ensureDir(subdirPath);
    console.log(`  Created: ${subdir}/`);
  }

  // Create README if not exists
  const readmePath = path.join(targetDir, 'README.md');
  if (!fs.existsSync(readmePath)) {
    const readme = `# .metaHub Workspace

Generated by DevOps CLI bootstrap.

## Structure

- \`tools/\` - CLI tools and scripts
- \`templates/\` - Template files
- \`ci/\` - CI/CD configurations
- \`k8s/\` - Kubernetes manifests
- \`helm/\` - Helm charts
- \`monitoring/\` - Monitoring configurations
- \`service/\` - Service source code
- \`docs/\` - Documentation

## Usage

See the main repository documentation for usage instructions.
`;
    fs.writeFileSync(readmePath, readme, 'utf-8');
    console.log('  Created: README.md');
  }

  console.log('\nBootstrap complete!');
}

// CLI entry point
if (process.argv[1].includes('bootstrap')) {
  const targetDir = resolveTargetDir(process.argv.slice(2));
  bootstrap(targetDir);
}

export { bootstrap };
