name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Would improve workflow
        - Important for productivity
        - Critical for adoption
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How much work do you estimate this requires?
      options:
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (1 week+)
        - Unknown

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This aligns with the project's goals
          required: true
