# ============================================================================
# Docker CI/CD Pipeline Template
# ============================================================================
# Reusable GitHub Actions workflow for building, testing, and deploying
# Docker containers with security scanning and quality checks
#
# Copy this file to .github/workflows/ in your project and customize as needed
# ============================================================================

name: Docker CI/CD

on:
  push:
    branches:
      - main
      - master
      - develop
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'package.json'
      - 'requirements.txt'
      - '.github/workflows/docker-ci.yml'
  pull_request:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'

jobs:
  # ==========================================================================
  # Stage 1: Validation & Linting
  # ==========================================================================
  validate:
    name: Validate Dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
          format: sarif
          output-file: hadolint-results.sarif

      - name: Upload Hadolint results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: hadolint-results.sarif

      - name: Verify Docker Compose (if exists)
        if: hashFiles('docker-compose.yml') != ''
        run: |
          docker compose config --quiet
          echo "✅ Docker Compose configuration is valid"

  # ==========================================================================
  # Stage 2: Build & Test
  # ==========================================================================
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: read
      packages: write

    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ steps.meta.outputs.version }}

      - name: Test container starts
        run: |
          docker run --rm -d --name test-container \
            ${{ steps.meta.outputs.tags }} || true
          sleep 5
          docker logs test-container || true
          docker stop test-container || true
          echo "✅ Container test completed"

  # ==========================================================================
  # Stage 3: Security Scanning
  # ==========================================================================
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build.outputs.image-tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  # Don't fail on vulnerabilities, just report

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Snyk Container Security scan
        if: github.event_name != 'pull_request'
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ needs.build.outputs.image-tag }}
          args: --severity-threshold=high --sarif-file-output=snyk-results.sarif

      - name: Upload Snyk results
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'snyk-results.sarif'

  # ==========================================================================
  # Stage 4: Quality & Performance
  # ==========================================================================
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check image size
        run: |
          docker pull ${{ needs.build.outputs.image-tag }}
          SIZE=$(docker images ${{ needs.build.outputs.image-tag }} --format "{{.Size}}")
          echo "Image size: $SIZE"

          # Extract size in MB for comparison
          SIZE_MB=$(docker images ${{ needs.build.outputs.image-tag }} --format "{{.Size}}" | grep -oP '\d+' | head -1)

          if [ "$SIZE_MB" -gt 1000 ]; then
            echo "⚠️ Warning: Image size exceeds 1GB"
          else
            echo "✅ Image size is acceptable"
          fi

      - name: Verify multi-stage build
        run: |
          if grep -q "AS builder" Dockerfile && grep -q "FROM.*AS production" Dockerfile; then
            echo "✅ Multi-stage build detected"
          else
            echo "⚠️ Warning: Consider using multi-stage builds for optimization"
          fi

      - name: Check for health check
        run: |
          if grep -q "HEALTHCHECK" Dockerfile; then
            echo "✅ Health check configured"
          else
            echo "⚠️ Warning: No health check found in Dockerfile"
          fi

  # ==========================================================================
  # Stage 5: Deploy
  # ==========================================================================
  deploy:
    name: Deploy to ${{ inputs.environment || 'staging' }}
    runs-on: ubuntu-latest
    needs: [build, security, quality]
    if: github.event_name != 'pull_request'
    environment:
      name: ${{ inputs.environment || 'staging' }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to environment
        id: deploy
        run: |
          echo "Deploying image: ${{ needs.build.outputs.image-tag }}"
          echo "Environment: ${{ inputs.environment || 'staging' }}"

          # Add your deployment commands here:
          # - kubectl apply
          # - docker compose up
          # - AWS ECS update-service
          # - etc.

          echo "url=https://${{ inputs.environment || 'staging' }}.example.com" >> $GITHUB_OUTPUT

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          # Add health check verification here
          # curl -f ${{ steps.deploy.outputs.url }}/health || exit 1
          echo "✅ Deployment verified"

      - name: Rollback on failure
        if: failure()
        run: |
          echo "❌ Deployment failed, initiating rollback..."
          # Add rollback commands here

  # ==========================================================================
  # Stage 6: Notification
  # ==========================================================================
  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()

    steps:
      - name: Notify on success
        if: needs.deploy.result == 'success'
        run: |
          echo "✅ Pipeline completed successfully"
          # Add notification logic (Slack, Discord, email, etc.)

      - name: Notify on failure
        if: needs.deploy.result == 'failure'
        run: |
          echo "❌ Pipeline failed"
          # Add notification logic
