services:
  benchbarrier:
    image: benchbarrier:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:8081', r => process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
  repz:
    image: repz:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:8080', r => process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
