name: CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

permissions:
  contents: read

jobs:
  build:
    uses: alaweimm90/alaweimm90/.github/workflows/reusable-ci.yml@main
    with:
      node-version: '20'
    secrets: inherit
