name: ATLAS CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  release:
    types: [published]

env:
  ATLAS_API_KEY: ${{ secrets.ATLAS_API_KEY }}
  ATLAS_API_URL: ${{ secrets.ATLAS_API_URL }}

jobs:
  # Security Scanning Job
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, python, java, go

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: ATLAS Code Review
        if: github.event_name == 'pull_request'
        run: |
          # Install ATLAS CLI if not present
          if ! command -v atlas &> /dev/null; then
            npm install -g @atlas/cli
          fi

          # Run ATLAS code review on changed files
          atlas task submit \
            --type code_review \
            --description "Review changes in PR #${{ github.event.number }}" \
            --context "{\"files\": $(git diff --name-only HEAD~1 | jq -R -s 'split("\n") | map(select(. != ""))')}" \
            --wait

  # Testing Job
  test:
    name: Automated Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        python-version: [3.8, 3.9, '3.10', '3.11']
        java-version: [11, 17, 21]
        go-version: [1.19, 1.20, 1.21]
        exclude:
          - node-version: 16.x
            python-version: 3.8
          - java-version: 11
            go-version: 1.19

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        if: matrix.node-version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup Python ${{ matrix.python-version }}
        if: matrix.python-version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Java ${{ matrix.java-version }}
        if: matrix.java-version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Setup Go ${{ matrix.go-version }}
        if: matrix.go-version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/pip
            ~/.m2/repository
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ matrix.python-version }}-${{ matrix.java-version }}-${{ matrix.go-version }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/requirements.txt', '**/pom.xml', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-${{ matrix.python-version }}-${{ matrix.java-version }}-${{ matrix.go-version }}-

      - name: Install Node.js dependencies
        if: matrix.node-version && hashFiles('package.json')
        run: npm ci

      - name: Install Python dependencies
        if: matrix.python-version && hashFiles('requirements.txt', 'setup.py', 'pyproject.toml')
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f setup.py ]; then pip install -e .; fi

      - name: Install Java dependencies
        if: matrix.java-version && hashFiles('pom.xml')
        run: mvn dependency:go-offline

      - name: Install Go dependencies
        if: matrix.go-version && hashFiles('go.mod')
        run: go mod download

      - name: Run linters
        run: |
          # Run available linters
          if command -v eslint &> /dev/null && [ -f "package.json" ]; then
            npm run lint || true
          fi
          if command -v flake8 &> /dev/null && [ -d "src" ]; then
            flake8 src/ || true
          fi
          if command -v golangci-lint &> /dev/null && [ -d "." ]; then
            golangci-lint run || true
          fi

      - name: Run tests
        run: |
          # Run tests for available languages
          if [ -f "package.json" ]; then
            npm test || true
          fi
          if [ -d "src" ] && [ -f "requirements.txt" ]; then
            python -m pytest || python -m unittest discover || true
          fi
          if [ -f "pom.xml" ]; then
            mvn test || true
          fi
          if [ -f "go.mod" ]; then
            go test ./... || true
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-${{ matrix.node-version }}-${{ matrix.python-version }}-${{ matrix.java-version }}-${{ matrix.go-version }}
          path: |
            **/test-results.xml
            **/coverage.xml
            **/target/surefire-reports/
            **/junit.xml

  # ATLAS Integration Testing
  atlas-integration:
    name: ATLAS Integration Tests
    runs-on: ubuntu-latest
    needs: [security-scan, test]
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install ATLAS CLI
        run: npm install -g @atlas/cli

      - name: Run ATLAS integration tests
        run: |
          # Run ATLAS-powered integration tests
          atlas task submit \
            --type analysis \
            --description "Run integration tests for changed components" \
            --context "{\"repository_path\": \".\", \"analysis_type\": \"integration\"}" \
            --wait

      - name: Generate test coverage report
        run: |
          atlas task submit \
            --type analysis \
            --description "Generate comprehensive test coverage report" \
            --context "{\"type\": \"coverage\", \"include_metrics\": true}" \
            --wait

  # Deployment Job
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [security-scan, test, atlas-integration]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: atlas-platform
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

          # Push images
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy to Kubernetes
        run: |
          # Update deployment with new image
          sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml

          # Apply Kubernetes manifests
          kubectl apply -f k8s/

          # Wait for rollout to complete
          kubectl rollout status deployment/atlas-platform

      - name: Run post-deployment tests
        run: |
          # Run ATLAS post-deployment validation
          atlas task submit \
            --type analysis \
            --description "Validate production deployment" \
            --context "{\"type\": \"deployment_validation\", \"environment\": \"production\"}" \
            --wait

      - name: Notify deployment success
        if: success()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
            -H 'Content-type: application/json' \
            -d "{\"text\":\"✅ ATLAS deployment to production completed successfully!\"}"

      - name: Notify deployment failure
        if: failure()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
            -H 'Content-type: application/json' \
            -d "{\"text\":\"❌ ATLAS deployment to production failed!\"}"

  # Performance Monitoring
  performance-monitoring:
    name: Performance Monitoring
    runs-on: ubuntu-latest
    needs: [deploy]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install ATLAS CLI
        run: npm install -g @atlas/cli

      - name: Run performance benchmarks
        run: |
          atlas task submit \
            --type analysis \
            --description "Run performance benchmarks against production" \
            --context "{\"type\": \"performance\", \"environment\": \"production\"}" \
            --wait

      - name: Generate performance report
        run: |
          atlas task submit \
            --type analysis \
            --description "Generate performance regression report" \
            --context "{\"type\": \"performance_report\", \"baseline_commit\": \"${{ github.event.before }}\", \"current_commit\": \"${{ github.sha }}\"}" \
            --wait

  # Documentation Update
  docs-update:
    name: Update Documentation
    runs-on: ubuntu-latest
    needs: [deploy]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Generate API documentation
        run: |
          # Generate API docs using ATLAS
          atlas task submit \
            --type analysis \
            --description "Generate comprehensive API documentation" \
            --context "{\"type\": \"documentation\", \"format\": \"html\", \"include_examples\": true}" \
            --wait

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          cname: docs.atlas-platform.com
