apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supertool-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project the application belongs to
  project: default

  # Source configuration
  source:
    # Git repository URL
    repoURL: https://github.com/username/supertool
    targetRevision: develop  # Use develop branch for dev environment
    path: devops/kubernetes/kustomize/overlays/dev

    # Kustomize-specific options
    kustomize:
      version: v5.0.0
      commonLabels:
        deployed-by: argocd
      commonAnnotations:
        argocd.argoproj.io/tracking-id: supertool-dev

  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  # Sync policy
  syncPolicy:
    automated:
      # Automatically sync when changes are detected
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  # Health assessment
  revisionHistoryLimit: 5
